### ISSUE TITLE
Data scope

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-latin-america-caribbean#1]
Hi @AnabelaARG
I'll be happy to help with setting the scope, but I need some help defining it.
Is it data FROM or ABOUT Argentina, Brazil, Colombia, Ecuador, Mexico and Uruguay?

**Comment by AnabelaARG** [comment]
Hi @MortenHofft !
Thank you for your help! The original idea was to got all the data about Argentina, Brazil, Colombia, Ecuador, Mexico, Peru and Uruguay. But, if is any trouble with that, with the data from those countries, we're OK. 
Let me know what is the best for the portal.

**Comment by MortenHofft** [comment]
I've changed the scope to be data ABOUT above mentioned countries. Filtering out records that state they are from those countries, but have coordinates in another country (likely a wrong countryCode)
